Add error handling section
jupeter/clean-code-php pull request #138
Opened 2018-01-04 08:26 UTC by hoseinz3

2018-01-04 10:27 UTC, Jibbarth commented on README.md
>    6. [Classes](#classes)
Even if Markdown replace correctly number in ordered list, we should update the other numbers for lisibility ?

2018-01-07 19:42 UTC, hoseinz3 commented
@TomasVotruba let me know if this PR has an issue ;)

2018-02-26 12:52 UTC, TomasVotruba commented
I didn't get the notification, will get to it :+1:

2018-02-26 19:27 UTC, TomasVotruba reviewed
I like the idea and added my review

2018-02-26 19:27 UTC, TomasVotruba commented on README.md
> +}
There is too much going on in this example. Shutting down, factories, logging, record validation.
I can't even find the *return code* part.

Example with as less code as possible expressing only the point you try to explain would be better.

2018-02-26 19:27 UTC, TomasVotruba commented on README.md
> +}
Here `getEmployees(): array` returns always array.
It should be maybe `getEmployees(): ?array`?

2018-02-26 19:27 UTC, TomasVotruba commented on README.md
> +    return is_null($this->employees) ? [] : $this->employees;
What about including `$empoyees` property and set it default value of `[]`?

2018-02-26 20:14 UTC, peter-gribanov commented on README.md
> +        if ($handle == DeviceHandle::INVALID) {
Are you sure that this is good?

2018-05-06 03:26 UTC, hoseinz3 commented on README.md
>    6. [Classes](#classes)
@Jibbarth i don't know, but fixed for consistency.

2018-05-06 03:26 UTC, hoseinz3 commented on README.md
> +}
@TomasVotruba i tried to use [clean code](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) book's example in error handling section, but i agree with you, i will try to show error handling in another way with simple code.

2018-05-07 12:55 UTC, peter-gribanov requested changes

2018-05-07 12:55 UTC, peter-gribanov commented on README.md
> +        if ($handle != DeviceHandle::INVALID) {
Same as [here](https://github.com/jupeter/clean-code-php/pull/138/files#r169024432). This condition will always be [`TRUE`](https://3v4l.org/4IDTa).

2018-08-21 07:50 UTC, TomasVotruba commented
Any plan to move with this or is that to be closed?

2018-09-16 00:29 UTC, TomasVotruba commented
Closing for no response from the author for almost a 3/4 year

2018-09-16 00:29 UTC, closed without merging